name: Unit Tests

on: [push]

jobs:
  cypress-run:
    runs-on: 
    - self-hosted
    - label-1

    node-version: [19.2.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      
      
      - name: Cypress run
      run: |
        uses: cypress-io/github-action@v2.24.3 # use the explicit version number
        with:
          build: npm run build
          start: npm start
